add problem to find roots of quadratic equation
lukew3/mathgenerator pull request #103
Opened 2020-10-16 18:26 UTC by ShivenTripathi

2020-10-16 21:45 UTC, lukew3 requested changes

2020-10-16 21:45 UTC, lukew3 commented on mathgenerator/mathgen.py
> +	solution = str[(-b+sqrt(b^2-4*a*c))/2*a,(-b-sqrt(b^2-4*a*c))/2*a]
This was causing some errors for me, specifically with the sqrt. Make sure you test your code.

2020-10-17 12:59 UTC, ShivenTripathi commented
made the changes, tested with some examples, also resolved the conflict

2020-10-17 16:54 UTC, lukew3 approved these changes

2020-10-17 16:54 UTC, merged